### ISSUE TITLE
HTTPS is forced

### ISSUE THREAD

**Issue by radiumatic** [pcarrier/srv.us#11]
Hi
It's mentioned in docs that using non-HTTP protocols(And abnormal TLS implementations?) is possible, But port 80 just redirects (301) to 443.
It's really appreciated if you would disable the forced HTTPS.
Thank you very much.

**Comment by pcarrier** [comment]
@nimagp TLS is required between the client and srv.us, and cannot be used between srv.us and the server.
There are no plans to support non-TLS between the client and srv.us as we use SNI for routing. What would be the use case where TLS is not desirable?

**Comment by radiumatic** [comment]
Thanks.
Mainly TLS implementations like uTLS and xTLS which are harder to detect and block in systems like GFW 
But a test showed that there is little difference in performance
