### ISSUE TITLE
Can't see a domain if -N option is set

### ISSUE THREAD

**Issue by stokito** [pcarrier/srv.us#18]
This is probably not a bug but maybe there is some solution.
The OpenWrt sshtunnel package ads the -N (and also -n) and after this I can't see a generated domain in logs.
But I can see the banner text. So maybe there is some workaround for this.

I created a PR for the OpenWrt sshtunnel were removed the problematic option https://github.com/openwrt/packages/pull/21263#issuecomment-1601708542

Still maybe someone else who just copied the ssh command from random site may be wondered what's wrong.

>  -N      Do not execute a remote command.  This is useful for just for‐
>              warding ports.  Refer to the description of SessionType in
>              ssh_config(5) for details.
>

**Comment by pcarrier** [comment]
Which banner text can you see? I'll have to dive further into the SSH protocol but my current understanding is that I need a text channel to output to once the port forwards have been sent, and `-N` prevents that.

**Comment by stokito** [comment]
ok, it's not possible to implement, closing. The localhost.run and remotemoe has a command to get a domain but that's another story.
